﻿<?php @session_start();if(!isset($_SESSION["email"])){@header("Location: index.php"); }include("ayar.php"); ?><?phpif(isset($_POST["konuac"])){$icerik = $_POST["icerik"];$email = $_SESSION["email"];if($_FILES["resim"]["name"] == ""){mysql_query("SET NAMES UTF8");mysql_query("INSERT INTO `mezdeke_gonderi`(`id`, `email`, `icerik`, `resim`, `begeni`, `yorum`) VALUES ('','$email','$icerik','resimyok','0','0')");}else{	$dizin="photos";	 $sorgu = "SELECT * FROM uyeler2 WHERE email='$email'";$admin_sorgu = mysql_query($sorgu, $mysqlbaglantisi) or die(mysql_error());$uyeler = mysql_fetch_array($admin_sorgu);$id = $uyeler['id'];if (!file_exists("$dizin/$id ")) { $kolustur = mkdir("$dizin/$id", 0777);} $kaynak         = $_FILES["resim"]["tmp_name"];    $resim          = $_FILES["resim"]["name"];    $rtipi         = $_FILES["resim"]["type"];    $rboyut         = $_FILES["resim"]["size"];    $ruzanti     = substr($resim, -4);  $yeniad         = substr(uniqid(md5(rand())), 0,35);    $yeniresim      = $yeniad.$ruzanti;    $dosya = $_POST["email"];    $hedef          = "photos";	if($rboyut < 8000000 && ($rtipi =="image/jpeg" || $rtipi =="image/gif" || $rtipi =="image/png" || $rtipi =="image/pjpeg")){		if(@move_uploaded_file($kaynak,$hedef.'/'.$id.'/'.$yeniresim)) {                $yol = $hedef.'/'.$id.'/'.$yeniresim;								mysql_query("SET NAME UTF8");mysql_query("INSERT INTO `mezdeke_gonderi`(`id`, `email`, `icerik`, `resim`, `begeni`, `yorum`) VALUES ('','$email','$icerik','$yol','0','0')"); echo '<meta http-equiv="refresh" content="0;URL=profil.php?id=$id">';				                           }						   else						   {						   						    echo "<script> alert('Yüklediğiniz Resim Çok Büyük Yada Resim Formatında Değil')</script>";						   }														}else						   {						   						    echo "<script> alert('Yüklediğiniz Resim Çok Büyük Yada Resim Formatında Değil')</script>";						   }}							}?><html><head>
       <link rel="stylesheet" type="text/css" href="style.css">
       <META http-equiv=content-type content=text/html;charset=UTF8>
 
 <link href='http://fonts.googleapis.com/css?family=Patrick+Hand' rel='stylesheet' type='text/css'>
 <script type="text/javascript" src="editor/scripts/widgEditor.js"></script>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
       <link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css">
       <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
       <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
       <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
       
       <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>	   	   <style type="text/css" media="all">	@import "editor/css/main.css";	@import "editor/css/widgEditor.css";</style>	   <style>	   	   ::-webkit-scrollbar {    width: 13px;} ::-webkit-scrollbar-track {    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);             border-radius: 10px;     } ::-webkit-scrollbar-thumb {    background-color:#111;    border-radius: 10px;       -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5); }	   	   </style>
    </head>
    <body style="overflow-y:scroll;">
    
<div id="yenikonualani" style="margin-left:auto;margin-right:auto;padding-left: 13px;padding-top: 10px;background-color: #FFF;width: 95%;min-height:300px;height:auto;color: #444;padding-top: 10px;font-family: 'PT Sans Narrow', sans-serif;background-color: #ffffff;box-shadow: 0 1px 2px #c9cccd;padding-bottom:15px;"><div class="iclogo" style="color:#111;font-size:25px;">Yeni Konu Aç<div style="margin-top:10px"></div><form method="post" enctype="multipart/form-data">><textarea id="noise" name="icerik" class="widgEditor nothing" style="font-family: 'PT Sans Narrow', sans-serif;">Yeni Konu Açın, Dikkat ! Spam Yapanlar Ceza Alacaktır</textarea><p style="font-size:14px;;float:left">Resim Yükle (Varsa) :</p> &nbsp;&nbsp;&nbsp;<input type="file" name="resim" style="background: #fff;font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', Helvetica, Arial, sans-serif;font-weight: 300;color: #8c8a8b;"><br><input type="submit" name="konuac" style="width: 200px;border-radius: 7px;background: #b6ee65;text-decoration: center;border: none;color: #51771a;padding: 10px;outline: none;font-size: 13px;border-bottom: 3px solid #307d63;cursor: pointer;margin-top:20px;" value="Konuyu Aç"></form></div></div>
			
</body></html>